# Generated by Django 3.1.6 on 2021-03-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name="Person's name")),
                ('seatNum', models.IntegerField(unique=True, verbose_name='Seat number')),
                ('ticketID', models.UUIDField(unique=True, verbose_name='Ticket ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
