# Generated by Django 3.1.6 on 2021-02-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name="Person's name")),
                ('seat_num', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Seat number')),
                ('ticket_id', models.UUIDField(unique=True, verbose_name='Ticket ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
