# Generated by Django 3.1.6 on 2021-03-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='id',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seatNum',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Seat number'),
        ),
    ]
