# Generated by Django 3.1.6 on 2021-02-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_num',
            field=models.IntegerField(unique=True, verbose_name='Seat number'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='ticket_id',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name='Ticket ID'),
        ),
    ]
