# Generated by Django 3.1.6 on 2021-02-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0002_auto_20210212_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat_num',
            new_name='seatNum',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='ticket_id',
            new_name='ticketID',
        ),
    ]
